version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: cmguilherme/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin      
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarqube_postgres_network
    restart: unless-stopped

  sonarqube:
    container_name: platform_service_sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar_platform_services
      - SONAR_JDBC_USERNAME=sonar_user
      - SONAR_JDBC_PASSWORD=sonar_admin
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarqube_postgres_network

networks:
  sonarqube_postgres_network:  
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_extensions:  